# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rasactl < Formula
  desc "rasactl deploys Rasa X / Enterprise on your local or remote Kubernetes cluster and manages Rasa X / Enterprise deployments."
  homepage "https://github.com/RasaHQ/rasactl"
  version "0.0.20"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RasaHQ/rasactl/releases/download/0.0.20/rasactl_0.0.20_darwin_amd64.tar.gz"
      sha256 "7d9747dbc445b250633f0719ffda60835077c2f578c55bdb10308fa3da1c87fb"
    end
    if Hardware::CPU.arm?
      url "https://github.com/RasaHQ/rasactl/releases/download/0.0.20/rasactl_0.0.20_darwin_arm64.tar.gz"
      sha256 "5325567ba4a877464a97f7456c8f12bef9f262e4bfd85def8e036cd75d1782a0"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/RasaHQ/rasactl/releases/download/0.0.20/rasactl_0.0.20_linux_amd64.tar.gz"
      sha256 "b6c80985dc429223ee338dd6cda6aa32632754f64aefe699f9cfb6aaad8d558b"
    end
  end

  def install
    bin.install "rasactl"
    bash_completion.install "completions/rasactl.bash" => "rasactl"
    zsh_completion.install "completions/rasactl.zsh" => "_rasactl"
    fish_completion.install "completions/rasactl.fish"
  end

  test do
    system "#{bin}/rasactl --version"
  end
end
